Repository alphaextensions/prime-sender, pull requests merged in 2025-07, with the labels that each got.

#118 Multiple Accont Buy Popup - Show Numbers Popup Design Update
  src/components/sections/MultipleAccountPopup.jsx
  src/styles/PricingPage/multipleAccountPopup.css
Labels: Under Review

#121 Location Issue fixed in Pricing Page
  src/components/Pages/Pricing.jsx
  src/components/context/index.jsx
Labels: Ready for Live, Staging

#120 New Unsubscribe added to dashboard
  .env
  src/components/Dashboard/settings.jsx
  src/components/widgets/profileSection/unSubscribe.jsx
Labels: Ready for Live
